<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Update="Persistence\Migrations\**\*.cs">
      <AutoGen>true</AutoGen>
      <DesignTime>true</DesignTime>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chevrere.SharedKernel\Chevrere.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\Chevrere.Modules.Identity.Domain\Chevrere.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Subscriptions\Chevrere.Modules.Subscriptions.Domain\Chevrere.Modules.Subscriptions.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Tenancy\Chevrere.Modules.Tenancy.Domain\Chevrere.Modules.Tenancy.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Catalog\Chevrere.Modules.Catalog.Domain\Chevrere.Modules.Catalog.Domain.csproj" />
  </ItemGroup>
</Project>
