// <auto-generated />
using System;
using Chevrere.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chevrere.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChevrereDbContext))]
    [Migration("20260914032319_AddConsumerDiscovery")]
    partial class AddConsumerDiscovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("procurement_goods_receipt_number_seq");

            modelBuilder.HasSequence("procurement_purchase_order_number_seq");

            modelBuilder.Entity("Chevrere.Infrastructure.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("previous_value");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_events_tenant_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_events_entity_type_entity_id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Chevrere.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Chevrere.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_users_tenant_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Catalog.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_categories_status");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Catalog.Domain.GlobalProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("brand");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("presentation");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_global_products");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_global_products_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_global_products_category_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_global_products_name");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ix_global_products_sku");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_global_products_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_global_products_status");

                    b.ToTable("global_products", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Catalog.Domain.StoreProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_store_products");

                    b.HasAlternateKey("TenantId", "StoreId", "GlobalProductId")
                        .HasName("ak_store_products_tenant_id_store_id_global_product_id");

                    b.HasIndex("GlobalProductId")
                        .HasDatabaseName("ix_store_products_global_product_id");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_store_products_is_enabled");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_store_products_tenant_id");

                    b.HasIndex("StoreId", "GlobalProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_products_store_id_global_product_id");

                    b.HasIndex("StoreId", "TenantId")
                        .HasDatabaseName("ix_store_products_store_id_tenant_id");

                    b.ToTable("store_products", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Consumer.Domain.StoreServiceArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (Point, 4326)")
                        .HasColumnName("location");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<int>("ServiceRadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("service_radius_meters");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_store_service_areas");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_store_service_areas_id_tenant_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_store_service_areas_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("StoreId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_service_areas_store_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_store_service_areas_tenant_id");

                    b.HasIndex("StoreId", "TenantId")
                        .HasDatabaseName("ix_store_service_areas_store_id_tenant_id");

                    b.ToTable("store_service_areas", null, t =>
                        {
                            t.HasCheckConstraint("ck_store_service_areas_radius_range", "service_radius_meters BETWEEN 100 AND 50000");
                        });
                });

            modelBuilder.Entity("Chevrere.Modules.Inventory.Domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<long>("OnHand")
                        .HasColumnType("bigint")
                        .HasColumnName("on_hand");

                    b.Property<long>("Reserved")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_inventory_items_id_tenant_id");

                    b.HasIndex("GlobalProductId")
                        .HasDatabaseName("ix_inventory_items_global_product_id");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_inventory_items_store_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_items_tenant_id");

                    b.HasIndex("StoreId", "TenantId")
                        .HasDatabaseName("ix_inventory_items_store_id_tenant_id");

                    b.HasIndex("TenantId", "StoreId", "GlobalProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_items_tenant_store_product");

                    b.ToTable("inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_items_on_hand_non_negative", "on_hand >= 0");

                            t.HasCheckConstraint("ck_inventory_items_reserved_lte_on_hand", "reserved <= on_hand");

                            t.HasCheckConstraint("ck_inventory_items_reserved_non_negative", "reserved >= 0");
                        });
                });

            modelBuilder.Entity("Chevrere.Modules.Inventory.Domain.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long>("OnHandAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("on_hand_after");

                    b.Property<long>("OnHandBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("on_hand_before");

                    b.Property<long>("OnHandDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("on_hand_delta");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_type");

                    b.Property<long>("ReservedAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_after");

                    b.Property<long>("ReservedBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_before");

                    b.Property<long>("ReservedDelta")
                        .HasColumnType("bigint")
                        .HasColumnName("reserved_delta");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventory_movements");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("ix_inventory_movements_reference_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inventory_movements_tenant_id");

                    b.HasIndex("InventoryItemId", "OccurredAt")
                        .HasDatabaseName("ix_inventory_movements_item_occurred_at");

                    b.HasIndex("InventoryItemId", "TenantId")
                        .HasDatabaseName("ix_inventory_movements_inventory_item_id_tenant_id");

                    b.HasIndex("Type", "ReferenceType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_movements_reference_unique")
                        .HasFilter("reference_id IS NOT NULL");

                    b.ToTable("inventory_movements", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Pricing.Domain.GlobalProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_global_product_prices");

                    b.HasIndex("GlobalProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_global_product_prices_current")
                        .HasFilter("valid_to IS NULL");

                    b.HasIndex("GlobalProductId", "ValidFrom")
                        .HasDatabaseName("ix_global_product_prices_product_valid_from");

                    b.ToTable("global_product_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_global_product_prices_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Chevrere.Modules.Pricing.Domain.StoreProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTimeOffset?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_store_product_prices");

                    b.HasIndex("GlobalProductId")
                        .HasDatabaseName("ix_store_product_prices_global_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_store_product_prices_tenant_id");

                    b.HasIndex("StoreId", "GlobalProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_store_product_prices_current")
                        .HasFilter("valid_to IS NULL");

                    b.HasIndex("StoreId", "TenantId")
                        .HasDatabaseName("ix_store_product_prices_store_id_tenant_id");

                    b.HasIndex("StoreId", "GlobalProductId", "ValidFrom")
                        .HasDatabaseName("ix_store_product_prices_store_product_valid_from");

                    b.HasIndex("TenantId", "StoreId", "GlobalProductId")
                        .HasDatabaseName("ix_store_product_prices_tenant_id_store_id_global_product_id");

                    b.ToTable("store_product_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_store_product_prices_amount_positive", "amount > 0");
                        });
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<string>("PurchaseOrderStatusAfter")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purchase_order_status_after");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("receipt_number");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_goods_receipts");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_goods_receipts_id_tenant_id");

                    b.HasAlternateKey("Id", "PurchaseOrderId", "TenantId")
                        .HasName("ak_goods_receipts_id_purchase_order_id_tenant_id");

                    b.HasIndex("PurchaseOrderId", "ReceivedAt")
                        .HasDatabaseName("ix_goods_receipts_order_received_at");

                    b.HasIndex("PurchaseOrderId", "TenantId")
                        .HasDatabaseName("ix_goods_receipts_purchase_order_id_tenant_id");

                    b.HasIndex("StoreId", "TenantId")
                        .HasDatabaseName("ix_goods_receipts_store_id_tenant_id");

                    b.HasIndex("SupplierId", "TenantId")
                        .HasDatabaseName("ix_goods_receipts_supplier_id_tenant_id");

                    b.HasIndex("TenantId", "ReceiptNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_goods_receipts_tenant_number");

                    b.ToTable("goods_receipts", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.GoodsReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("goods_receipt_id");

                    b.Property<Guid?>("InventoryMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_movement_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<Guid>("PurchaseOrderItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_item_id");

                    b.Property<long>("ReceivedAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("received_after");

                    b.Property<long>("ReceivedBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("received_before");

                    b.Property<long>("ReceivedQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("received_quantity");

                    b.Property<long>("RemainingAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("remaining_after");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_goods_receipt_items");

                    b.HasIndex("GlobalProductId")
                        .HasDatabaseName("ix_goods_receipt_items_global_product_id");

                    b.HasIndex("InventoryMovementId")
                        .HasDatabaseName("ix_goods_receipt_items_inventory_movement_id");

                    b.HasIndex("PurchaseOrderId")
                        .HasDatabaseName("ix_goods_receipt_items_purchase_order_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_goods_receipt_items_tenant_id");

                    b.HasIndex("GoodsReceiptId", "PurchaseOrderItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_goods_receipt_items_receipt_order_item");

                    b.HasIndex("GoodsReceiptId", "PurchaseOrderId", "TenantId")
                        .HasDatabaseName("ix_goods_receipt_items_goods_receipt_id_purchase_order_id_tena");

                    b.HasIndex("PurchaseOrderItemId", "PurchaseOrderId", "TenantId", "GlobalProductId")
                        .HasDatabaseName("ix_goods_receipt_items_purchase_order_item_id_purchase_order_i");

                    b.ToTable("goods_receipt_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_goods_receipt_items_received_before_non_negative", "received_before >= 0");

                            t.HasCheckConstraint("ck_goods_receipt_items_received_chain", "received_after = received_before + received_quantity");

                            t.HasCheckConstraint("ck_goods_receipt_items_received_positive", "received_quantity > 0");

                            t.HasCheckConstraint("ck_goods_receipt_items_remaining_non_negative", "remaining_after >= 0");
                        });
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_purchase_orders");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_purchase_orders_id_tenant_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id");

                    b.HasIndex("StoreId", "TenantId")
                        .HasDatabaseName("ix_purchase_orders_store_id_tenant_id");

                    b.HasIndex("SupplierId", "TenantId")
                        .HasDatabaseName("ix_purchase_orders_supplier_id_tenant_id");

                    b.HasIndex("TenantId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_orders_tenant_number");

                    b.HasIndex("TenantId", "StoreId", "Status")
                        .HasDatabaseName("ix_purchase_orders_tenant_store_status");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GlobalProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("global_product_id");

                    b.Property<long>("OrderedQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("ordered_quantity");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_order_id");

                    b.Property<long>("ReceivedQuantity")
                        .HasColumnType("bigint")
                        .HasColumnName("received_quantity");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("UnitCostAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost_amount");

                    b.Property<string>("UnitCostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("unit_cost_currency");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_purchase_order_items");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_purchase_order_items_id_tenant_id");

                    b.HasAlternateKey("Id", "PurchaseOrderId", "TenantId", "GlobalProductId")
                        .HasName("ak_purchase_order_items_id_purchase_order_id_tenant_id_global_pr");

                    b.HasIndex("GlobalProductId")
                        .HasDatabaseName("ix_purchase_order_items_global_product_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_purchase_order_items_tenant_id");

                    b.HasIndex("PurchaseOrderId", "GlobalProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_order_items_order_product");

                    b.HasIndex("PurchaseOrderId", "TenantId")
                        .HasDatabaseName("ix_purchase_order_items_purchase_order_id_tenant_id");

                    b.HasIndex("TenantId", "StoreId", "GlobalProductId")
                        .HasDatabaseName("ix_purchase_order_items_tenant_id_store_id_global_product_id");

                    b.ToTable("purchase_order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchase_order_items_ordered_positive", "ordered_quantity > 0");

                            t.HasCheckConstraint("ck_purchase_order_items_received_lte_ordered", "received_quantity <= ordered_quantity");

                            t.HasCheckConstraint("ck_purchase_order_items_received_non_negative", "received_quantity >= 0");

                            t.HasCheckConstraint("ck_purchase_order_items_unit_cost_positive", "unit_cost_amount > 0");
                        });
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("ContactName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("contact_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxIdentification")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_identification");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_suppliers_id_tenant_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_suppliers_is_active");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_suppliers_tenant_code");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Subscriptions.Domain.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("billing_period");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_code");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Subscriptions.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_start");

                    b.Property<DateTimeOffset?>("GracePeriodUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_until");

                    b.Property<DateTimeOffset>("NextBillingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_billing_date");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("suspension_reason");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_subscriptions_status");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_tenant_active")
                        .HasFilter("status <> 'Cancelled'");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Tenancy.Domain.Franchisee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("identification_number");

                    b.Property<string>("IdentificationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("identification_type");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_franchisees");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_franchisees_id_tenant_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_franchisees_code");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_franchisees_identification_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_franchisees_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_franchisees_tenant_id");

                    b.HasIndex("TradeName", "LegalName")
                        .HasDatabaseName("ix_franchisees_trade_name_legal_name");

                    b.ToTable("franchisees", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Tenancy.Domain.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AddressInternal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address_internal");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FranchiseeId")
                        .HasColumnType("uuid")
                        .HasColumnName("franchisee_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.HasAlternateKey("Id", "TenantId")
                        .HasName("ak_stores_id_tenant_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_stores_status");

                    b.HasIndex("FranchiseeId", "TenantId")
                        .HasDatabaseName("ix_stores_franchisee_id_tenant_id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_stores_tenant_id_code");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Tenancy.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tenants_status");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Chevrere.SharedKernel.Idempotency.IdempotentOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotent_operations");

                    b.HasIndex("TenantId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotent_operations_tenant_operation_key");

                    b.ToTable("idempotent_operations", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Chevrere.Modules.Catalog.Domain.GlobalProduct", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_global_products_categories_category_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Catalog.Domain.StoreProduct", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_products_global_products_global_product_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_products_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_products_stores_store_id_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Consumer.Domain.StoreServiceArea", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_service_areas_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_service_areas_stores_store_id_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Inventory.Domain.InventoryItem", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_global_products_global_product_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_stores_store_id_tenant_id");

                    b.HasOne("Chevrere.Modules.Catalog.Domain.StoreProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StoreId", "GlobalProductId")
                        .HasPrincipalKey("TenantId", "StoreId", "GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_store_products_tenant_id_store_id_global_pr");
                });

            modelBuilder.Entity("Chevrere.Modules.Inventory.Domain.InventoryMovement", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Inventory.Domain.InventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_movements_inventory_items_inventory_item_id_tenan");
                });

            modelBuilder.Entity("Chevrere.Modules.Pricing.Domain.GlobalProductPrice", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_global_product_prices_global_products_global_product_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Pricing.Domain.StoreProductPrice", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_product_prices_global_products_global_product_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_product_prices_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_product_prices_stores_store_id_tenant_id");

                    b.HasOne("Chevrere.Modules.Catalog.Domain.StoreProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StoreId", "GlobalProductId")
                        .HasPrincipalKey("TenantId", "StoreId", "GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_store_product_prices_store_products_tenant_id_store_id_glob");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.GoodsReceipt", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipts_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Procurement.Domain.PurchaseOrder", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipts_purchase_orders_purchase_order_id_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipts_stores_store_id_tenant_id");

                    b.HasOne("Chevrere.Modules.Procurement.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipts_suppliers_supplier_id_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.GoodsReceiptItem", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_items_global_products_global_product_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_items_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Procurement.Domain.GoodsReceipt", null)
                        .WithMany("Items")
                        .HasForeignKey("GoodsReceiptId", "PurchaseOrderId", "TenantId")
                        .HasPrincipalKey("Id", "PurchaseOrderId", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_items_goods_receipts_goods_receipt_id_purchas");

                    b.HasOne("Chevrere.Modules.Procurement.Domain.PurchaseOrderItem", null)
                        .WithMany()
                        .HasForeignKey("PurchaseOrderItemId", "PurchaseOrderId", "TenantId", "GlobalProductId")
                        .HasPrincipalKey("Id", "PurchaseOrderId", "TenantId", "GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_goods_receipt_items_purchase_order_items_purchase_order_ite");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Store", null)
                        .WithMany()
                        .HasForeignKey("StoreId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_stores_store_id_tenant_id");

                    b.HasOne("Chevrere.Modules.Procurement.Domain.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_orders_suppliers_supplier_id_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.PurchaseOrderItem", b =>
                {
                    b.HasOne("Chevrere.Modules.Catalog.Domain.GlobalProduct", null)
                        .WithMany()
                        .HasForeignKey("GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_global_products_global_product_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Procurement.Domain.PurchaseOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_purchase_orders_purchase_order_id_tena");

                    b.HasOne("Chevrere.Modules.Catalog.Domain.StoreProduct", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "StoreId", "GlobalProductId")
                        .HasPrincipalKey("TenantId", "StoreId", "GlobalProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_order_items_store_products_tenant_id_store_id_glob");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.Supplier", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_suppliers_tenants_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Subscriptions.Domain.Subscription", b =>
                {
                    b.HasOne("Chevrere.Modules.Subscriptions.Domain.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_tenants_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Tenancy.Domain.Franchisee", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_franchisees_tenants_tenant_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Tenancy.Domain.Store", b =>
                {
                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stores_tenants_tenant_id");

                    b.HasOne("Chevrere.Modules.Tenancy.Domain.Franchisee", null)
                        .WithMany()
                        .HasForeignKey("FranchiseeId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stores_franchisees_franchisee_id_tenant_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Chevrere.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Chevrere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Chevrere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Chevrere.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Chevrere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Chevrere.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.GoodsReceipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Chevrere.Modules.Procurement.Domain.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
