// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Chevrere.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class HardenGoodsReceiptItemIntegrity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_goods_receipt_items_goods_receipts_goods_receipt_id_tenant_",
                table: "goods_receipt_items");

            migrationBuilder.DropForeignKey(
                name: "fk_goods_receipt_items_purchase_order_items_purchase_order_ite",
                table: "goods_receipt_items");

            migrationBuilder.DropIndex(
                name: "ix_goods_receipt_items_goods_receipt_id_tenant_id",
                table: "goods_receipt_items");

            migrationBuilder.DropIndex(
                name: "ix_goods_receipt_items_purchase_order_item_id_tenant_id",
                table: "goods_receipt_items");

            migrationBuilder.AddColumn<Guid>(
                name: "purchase_order_id",
                table: "goods_receipt_items",
                type: "uuid",
                nullable: true);

            migrationBuilder.Sql(
                """
                UPDATE goods_receipt_items AS i
                SET purchase_order_id = r.purchase_order_id
                FROM goods_receipts AS r
                WHERE i.goods_receipt_id = r.id;
                """);

            migrationBuilder.AlterColumn<Guid>(
                name: "purchase_order_id",
                table: "goods_receipt_items",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AddUniqueConstraint(
                name: "ak_purchase_order_items_id_purchase_order_id_tenant_id_global_pr",
                table: "purchase_order_items",
                columns: new[] { "id", "purchase_order_id", "tenant_id", "global_product_id" });

            migrationBuilder.AddUniqueConstraint(
                name: "ak_goods_receipts_id_purchase_order_id_tenant_id",
                table: "goods_receipts",
                columns: new[] { "id", "purchase_order_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_goods_receipt_id_purchase_order_id_tena",
                table: "goods_receipt_items",
                columns: new[] { "goods_receipt_id", "purchase_order_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_purchase_order_id",
                table: "goods_receipt_items",
                column: "purchase_order_id");

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_purchase_order_item_id_purchase_order_i",
                table: "goods_receipt_items",
                columns: new[] { "purchase_order_item_id", "purchase_order_id", "tenant_id", "global_product_id" });

            migrationBuilder.AddForeignKey(
                name: "fk_goods_receipt_items_goods_receipts_goods_receipt_id_purchas",
                table: "goods_receipt_items",
                columns: new[] { "goods_receipt_id", "purchase_order_id", "tenant_id" },
                principalTable: "goods_receipts",
                principalColumns: new[] { "id", "purchase_order_id", "tenant_id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_goods_receipt_items_purchase_order_items_purchase_order_ite",
                table: "goods_receipt_items",
                columns: new[] { "purchase_order_item_id", "purchase_order_id", "tenant_id", "global_product_id" },
                principalTable: "purchase_order_items",
                principalColumns: new[] { "id", "purchase_order_id", "tenant_id", "global_product_id" },
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_goods_receipt_items_goods_receipts_goods_receipt_id_purchas",
                table: "goods_receipt_items");

            migrationBuilder.DropForeignKey(
                name: "fk_goods_receipt_items_purchase_order_items_purchase_order_ite",
                table: "goods_receipt_items");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_purchase_order_items_id_purchase_order_id_tenant_id_global_pr",
                table: "purchase_order_items");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_goods_receipts_id_purchase_order_id_tenant_id",
                table: "goods_receipts");

            migrationBuilder.DropIndex(
                name: "ix_goods_receipt_items_goods_receipt_id_purchase_order_id_tena",
                table: "goods_receipt_items");

            migrationBuilder.DropIndex(
                name: "ix_goods_receipt_items_purchase_order_id",
                table: "goods_receipt_items");

            migrationBuilder.DropIndex(
                name: "ix_goods_receipt_items_purchase_order_item_id_purchase_order_i",
                table: "goods_receipt_items");

            migrationBuilder.DropColumn(
                name: "purchase_order_id",
                table: "goods_receipt_items");

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_goods_receipt_id_tenant_id",
                table: "goods_receipt_items",
                columns: new[] { "goods_receipt_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_purchase_order_item_id_tenant_id",
                table: "goods_receipt_items",
                columns: new[] { "purchase_order_item_id", "tenant_id" });

            migrationBuilder.AddForeignKey(
                name: "fk_goods_receipt_items_goods_receipts_goods_receipt_id_tenant_",
                table: "goods_receipt_items",
                columns: new[] { "goods_receipt_id", "tenant_id" },
                principalTable: "goods_receipts",
                principalColumns: new[] { "id", "tenant_id" },
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_goods_receipt_items_purchase_order_items_purchase_order_ite",
                table: "goods_receipt_items",
                columns: new[] { "purchase_order_item_id", "tenant_id" },
                principalTable: "purchase_order_items",
                principalColumns: new[] { "id", "tenant_id" },
                onDelete: ReferentialAction.Restrict);
        }
    }
}
