sonar.projectKey=chevrere
sonar.projectName=YaaJuu
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/Migrations/**,**/bin/**,**/obj/**
sonar.coverage.exclusions=**/Migrations/**,**/Program.cs,**/YaaJuuDbContextFactory.cs
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
