<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\YaaJuu.Modules.Orders.Application\YaaJuu.Modules.Orders.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\YaaJuu.Infrastructure\YaaJuu.Infrastructure.csproj" />
  </ItemGroup>
</Project>
