<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Chevrere.SharedKernel\Chevrere.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Chevrere.Modules.Orders.Infrastructure" />
    <InternalsVisibleTo Include="Chevrere.UnitTests" />
    <InternalsVisibleTo Include="Chevrere.IntegrationTests" />
  </ItemGroup>
</Project>
