<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\YaaJuu.Modules.Consumer.Application\YaaJuu.Modules.Consumer.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\YaaJuu.Infrastructure\YaaJuu.Infrastructure.csproj" />
  </ItemGroup>
</Project>
