<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Chevrere.Modules.Catalog.Application\Chevrere.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Chevrere.Infrastructure\Chevrere.Infrastructure.csproj" />
  </ItemGroup>
</Project>
