// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddInventoryModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "idempotent_operations",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    operation = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    idempotency_key = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    request_hash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    resource_id = table.Column<Guid>(type: "uuid", nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_idempotent_operations", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "inventory_items",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    on_hand = table.Column<long>(type: "bigint", nullable: false),
                    reserved = table.Column<long>(type: "bigint", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inventory_items", x => x.id);
                    table.UniqueConstraint("ak_inventory_items_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.CheckConstraint("ck_inventory_items_on_hand_non_negative", "on_hand >= 0");
                    table.CheckConstraint("ck_inventory_items_reserved_lte_on_hand", "reserved <= on_hand");
                    table.CheckConstraint("ck_inventory_items_reserved_non_negative", "reserved >= 0");
                    table.ForeignKey(
                        name: "fk_inventory_items_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_inventory_items_store_products_tenant_id_store_id_global_pr",
                        columns: x => new { x.tenant_id, x.store_id, x.global_product_id },
                        principalTable: "store_products",
                        principalColumns: new[] { "tenant_id", "store_id", "global_product_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_inventory_items_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_inventory_items_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "inventory_movements",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    inventory_item_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    type = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    on_hand_delta = table.Column<long>(type: "bigint", nullable: false),
                    reserved_delta = table.Column<long>(type: "bigint", nullable: false),
                    on_hand_before = table.Column<long>(type: "bigint", nullable: false),
                    on_hand_after = table.Column<long>(type: "bigint", nullable: false),
                    reserved_before = table.Column<long>(type: "bigint", nullable: false),
                    reserved_after = table.Column<long>(type: "bigint", nullable: false),
                    reason = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    reference_type = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    reference_id = table.Column<Guid>(type: "uuid", nullable: true),
                    occurred_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    actor_user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    correlation_id = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inventory_movements", x => x.id);
                    table.ForeignKey(
                        name: "fk_inventory_movements_inventory_items_inventory_item_id_tenan",
                        columns: x => new { x.inventory_item_id, x.tenant_id },
                        principalTable: "inventory_items",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_inventory_movements_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_idempotent_operations_tenant_operation_key",
                table: "idempotent_operations",
                columns: new[] { "tenant_id", "operation", "idempotency_key" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_inventory_items_global_product_id",
                table: "inventory_items",
                column: "global_product_id");

            migrationBuilder.CreateIndex(
                name: "ix_inventory_items_store_id",
                table: "inventory_items",
                column: "store_id");

            migrationBuilder.CreateIndex(
                name: "ix_inventory_items_store_id_tenant_id",
                table: "inventory_items",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_items_tenant_id",
                table: "inventory_items",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_inventory_items_tenant_store_product",
                table: "inventory_items",
                columns: new[] { "tenant_id", "store_id", "global_product_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_inventory_movements_inventory_item_id_tenant_id",
                table: "inventory_movements",
                columns: new[] { "inventory_item_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_movements_item_occurred_at",
                table: "inventory_movements",
                columns: new[] { "inventory_item_id", "occurred_at" });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_movements_reference_id",
                table: "inventory_movements",
                column: "reference_id");

            migrationBuilder.CreateIndex(
                name: "ix_inventory_movements_tenant_id",
                table: "inventory_movements",
                column: "tenant_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "idempotent_operations");

            migrationBuilder.DropTable(
                name: "inventory_movements");

            migrationBuilder.DropTable(
                name: "inventory_items");
        }
    }
}
