// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddOrdersAndInventoryReservations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateSequence(
                name: "orders_order_number_seq");

            migrationBuilder.AddUniqueConstraint(
                name: "ak_inventory_items_id_tenant_store_product",
                table: "inventory_items",
                columns: new[] { "id", "tenant_id", "store_id", "global_product_id" });

            migrationBuilder.CreateTable(
                name: "carts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    consumer_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    converted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_carts", x => x.id);
                    table.UniqueConstraint("ak_carts_id_consumer_tenant_store", x => new { x.id, x.consumer_user_id, x.tenant_id, x.store_id });
                    table.ForeignKey(
                        name: "fk_carts_asp_net_users_consumer_user_id",
                        column: x => x.consumer_user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_carts_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_carts_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "inventory_reservations",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    inventory_item_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    reference_type = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    reference_id = table.Column<Guid>(type: "uuid", nullable: false),
                    quantity = table.Column<long>(type: "bigint", nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    released_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    committed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    expires_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_inventory_reservations", x => x.id);
                    table.CheckConstraint("ck_inventory_reservations_quantity_positive", "quantity > 0");
                    table.ForeignKey(
                        name: "fk_inventory_reservations_inventory_items_inventory_item_id_te",
                        columns: x => new { x.inventory_item_id, x.tenant_id, x.store_id, x.global_product_id },
                        principalTable: "inventory_items",
                        principalColumns: new[] { "id", "tenant_id", "store_id", "global_product_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_inventory_reservations_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_inventory_reservations_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "cart_items",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    cart_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    quantity = table.Column<long>(type: "bigint", nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_cart_items", x => x.id);
                    table.CheckConstraint("ck_cart_items_quantity_positive", "quantity > 0");
                    table.ForeignKey(
                        name: "fk_cart_items_carts_cart_id",
                        column: x => x.cart_id,
                        principalTable: "carts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_cart_items_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_cart_items_store_products_tenant_id_store_id_global_product",
                        columns: x => new { x.tenant_id, x.store_id, x.global_product_id },
                        principalTable: "store_products",
                        principalColumns: new[] { "tenant_id", "store_id", "global_product_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_cart_items_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "orders",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    number = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    consumer_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    source_cart_id = table.Column<Guid>(type: "uuid", nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    subtotal_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    total_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    expires_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    cancelled_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    cancel_reason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_orders", x => x.id);
                    table.UniqueConstraint("ak_orders_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.CheckConstraint("ck_orders_subtotal_positive", "subtotal_amount > 0");
                    table.CheckConstraint("ck_orders_total_positive", "total_amount > 0");
                    table.ForeignKey(
                        name: "fk_orders_asp_net_users_consumer_user_id",
                        column: x => x.consumer_user_id,
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_orders_carts_source_cart_id_consumer_user_id_tenant_id_stor",
                        columns: x => new { x.source_cart_id, x.consumer_user_id, x.tenant_id, x.store_id },
                        principalTable: "carts",
                        principalColumns: new[] { "id", "consumer_user_id", "tenant_id", "store_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_orders_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_orders_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "order_items",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    order_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    sku = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    name = table.Column<string>(type: "character varying(160)", maxLength: 160, nullable: false),
                    brand = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    presentation = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
                    quantity = table.Column<long>(type: "bigint", nullable: false),
                    unit_price_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    unit_price_currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    line_total_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_order_items", x => x.id);
                    table.CheckConstraint("ck_order_items_line_total_positive", "line_total_amount > 0");
                    table.CheckConstraint("ck_order_items_quantity_positive", "quantity > 0");
                    table.CheckConstraint("ck_order_items_unit_price_positive", "unit_price_amount > 0");
                    table.ForeignKey(
                        name: "fk_order_items_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_order_items_orders_order_id_tenant_id",
                        columns: x => new { x.order_id, x.tenant_id },
                        principalTable: "orders",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_order_items_store_products_tenant_id_store_id_global_produc",
                        columns: x => new { x.tenant_id, x.store_id, x.global_product_id },
                        principalTable: "store_products",
                        principalColumns: new[] { "tenant_id", "store_id", "global_product_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_order_items_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_cart_items_cart_product",
                table: "cart_items",
                columns: new[] { "cart_id", "global_product_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_cart_items_global_product_id",
                table: "cart_items",
                column: "global_product_id");

            migrationBuilder.CreateIndex(
                name: "ix_cart_items_tenant_id",
                table: "cart_items",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_cart_items_tenant_id_store_id_global_product_id",
                table: "cart_items",
                columns: new[] { "tenant_id", "store_id", "global_product_id" });

            migrationBuilder.CreateIndex(
                name: "ix_carts_consumer_active",
                table: "carts",
                column: "consumer_user_id",
                unique: true,
                filter: "status = 'Active'");

            migrationBuilder.CreateIndex(
                name: "ix_carts_store_id_tenant_id",
                table: "carts",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_carts_tenant_id_store_id",
                table: "carts",
                columns: new[] { "tenant_id", "store_id" });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_reservations_inventory_item_id",
                table: "inventory_reservations",
                column: "inventory_item_id");

            migrationBuilder.CreateIndex(
                name: "ix_inventory_reservations_inventory_item_id_tenant_id_store_id",
                table: "inventory_reservations",
                columns: new[] { "inventory_item_id", "tenant_id", "store_id", "global_product_id" });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_reservations_reference",
                table: "inventory_reservations",
                columns: new[] { "reference_type", "reference_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_inventory_reservations_store_id_tenant_id",
                table: "inventory_reservations",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_reservations_tenant_store_status",
                table: "inventory_reservations",
                columns: new[] { "tenant_id", "store_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_order_items_global_product_id",
                table: "order_items",
                column: "global_product_id");

            migrationBuilder.CreateIndex(
                name: "ix_order_items_order_id_tenant_id",
                table: "order_items",
                columns: new[] { "order_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_order_items_order_product",
                table: "order_items",
                columns: new[] { "order_id", "global_product_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_order_items_tenant_id",
                table: "order_items",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_order_items_tenant_id_store_id_global_product_id",
                table: "order_items",
                columns: new[] { "tenant_id", "store_id", "global_product_id" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_consumer_created_at",
                table: "orders",
                columns: new[] { "consumer_user_id", "created_at" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_source_cart_id",
                table: "orders",
                column: "source_cart_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_orders_source_cart_id_consumer_user_id_tenant_id_store_id",
                table: "orders",
                columns: new[] { "source_cart_id", "consumer_user_id", "tenant_id", "store_id" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_status_expires_at",
                table: "orders",
                columns: new[] { "status", "expires_at" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_store_id_tenant_id",
                table: "orders",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_number",
                table: "orders",
                columns: new[] { "tenant_id", "number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_orders_tenant_store_created_at",
                table: "orders",
                columns: new[] { "tenant_id", "store_id", "created_at" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cart_items");

            migrationBuilder.DropTable(
                name: "inventory_reservations");

            migrationBuilder.DropTable(
                name: "order_items");

            migrationBuilder.DropTable(
                name: "orders");

            migrationBuilder.DropTable(
                name: "carts");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_inventory_items_id_tenant_store_product",
                table: "inventory_items");

            migrationBuilder.DropSequence(
                name: "orders_order_number_seq");
        }
    }
}
