// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddProcurementModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateSequence(
                name: "procurement_goods_receipt_number_seq");

            migrationBuilder.CreateSequence(
                name: "procurement_purchase_order_number_seq");

            migrationBuilder.CreateTable(
                name: "suppliers",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    code = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                    name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    tax_identification = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    contact_name = table.Column<string>(type: "character varying(160)", maxLength: 160, nullable: true),
                    email = table.Column<string>(type: "character varying(256)", maxLength: 256, nullable: true),
                    phone = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: true),
                    address = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_suppliers", x => x.id);
                    table.UniqueConstraint("ak_suppliers_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.ForeignKey(
                        name: "fk_suppliers_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "purchase_orders",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    supplier_id = table.Column<Guid>(type: "uuid", nullable: false),
                    number = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    approved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    cancelled_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    cancel_reason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_purchase_orders", x => x.id);
                    table.UniqueConstraint("ak_purchase_orders_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.ForeignKey(
                        name: "fk_purchase_orders_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_purchase_orders_suppliers_supplier_id_tenant_id",
                        columns: x => new { x.supplier_id, x.tenant_id },
                        principalTable: "suppliers",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_purchase_orders_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "goods_receipts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    purchase_order_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    supplier_id = table.Column<Guid>(type: "uuid", nullable: false),
                    receipt_number = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
                    received_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    actor_user_id = table.Column<Guid>(type: "uuid", nullable: true),
                    correlation_id = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    purchase_order_status_after = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_goods_receipts", x => x.id);
                    table.UniqueConstraint("ak_goods_receipts_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.ForeignKey(
                        name: "fk_goods_receipts_purchase_orders_purchase_order_id_tenant_id",
                        columns: x => new { x.purchase_order_id, x.tenant_id },
                        principalTable: "purchase_orders",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_goods_receipts_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_goods_receipts_suppliers_supplier_id_tenant_id",
                        columns: x => new { x.supplier_id, x.tenant_id },
                        principalTable: "suppliers",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_goods_receipts_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "purchase_order_items",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    purchase_order_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    ordered_quantity = table.Column<long>(type: "bigint", nullable: false),
                    received_quantity = table.Column<long>(type: "bigint", nullable: false),
                    unit_cost_amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    unit_cost_currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_purchase_order_items", x => x.id);
                    table.UniqueConstraint("ak_purchase_order_items_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.CheckConstraint("ck_purchase_order_items_ordered_positive", "ordered_quantity > 0");
                    table.CheckConstraint("ck_purchase_order_items_received_lte_ordered", "received_quantity <= ordered_quantity");
                    table.CheckConstraint("ck_purchase_order_items_received_non_negative", "received_quantity >= 0");
                    table.CheckConstraint("ck_purchase_order_items_unit_cost_positive", "unit_cost_amount > 0");
                    table.ForeignKey(
                        name: "fk_purchase_order_items_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_purchase_order_items_purchase_orders_purchase_order_id_tena",
                        columns: x => new { x.purchase_order_id, x.tenant_id },
                        principalTable: "purchase_orders",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_purchase_order_items_store_products_tenant_id_store_id_glob",
                        columns: x => new { x.tenant_id, x.store_id, x.global_product_id },
                        principalTable: "store_products",
                        principalColumns: new[] { "tenant_id", "store_id", "global_product_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_purchase_order_items_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "goods_receipt_items",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    goods_receipt_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    purchase_order_item_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    received_quantity = table.Column<long>(type: "bigint", nullable: false),
                    received_before = table.Column<long>(type: "bigint", nullable: false),
                    received_after = table.Column<long>(type: "bigint", nullable: false),
                    remaining_after = table.Column<long>(type: "bigint", nullable: false),
                    inventory_movement_id = table.Column<Guid>(type: "uuid", nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_goods_receipt_items", x => x.id);
                    table.CheckConstraint("ck_goods_receipt_items_received_before_non_negative", "received_before >= 0");
                    table.CheckConstraint("ck_goods_receipt_items_received_chain", "received_after = received_before + received_quantity");
                    table.CheckConstraint("ck_goods_receipt_items_received_positive", "received_quantity > 0");
                    table.CheckConstraint("ck_goods_receipt_items_remaining_non_negative", "remaining_after >= 0");
                    table.ForeignKey(
                        name: "fk_goods_receipt_items_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_goods_receipt_items_goods_receipts_goods_receipt_id_tenant_",
                        columns: x => new { x.goods_receipt_id, x.tenant_id },
                        principalTable: "goods_receipts",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "fk_goods_receipt_items_purchase_order_items_purchase_order_ite",
                        columns: x => new { x.purchase_order_item_id, x.tenant_id },
                        principalTable: "purchase_order_items",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_goods_receipt_items_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_inventory_movements_reference_unique",
                table: "inventory_movements",
                columns: new[] { "type", "reference_type", "reference_id" },
                unique: true,
                filter: "reference_id IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_global_product_id",
                table: "goods_receipt_items",
                column: "global_product_id");

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_goods_receipt_id_tenant_id",
                table: "goods_receipt_items",
                columns: new[] { "goods_receipt_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_inventory_movement_id",
                table: "goods_receipt_items",
                column: "inventory_movement_id");

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_purchase_order_item_id_tenant_id",
                table: "goods_receipt_items",
                columns: new[] { "purchase_order_item_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_receipt_order_item",
                table: "goods_receipt_items",
                columns: new[] { "goods_receipt_id", "purchase_order_item_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipt_items_tenant_id",
                table: "goods_receipt_items",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipts_order_received_at",
                table: "goods_receipts",
                columns: new[] { "purchase_order_id", "received_at" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipts_purchase_order_id_tenant_id",
                table: "goods_receipts",
                columns: new[] { "purchase_order_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipts_store_id_tenant_id",
                table: "goods_receipts",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipts_supplier_id_tenant_id",
                table: "goods_receipts",
                columns: new[] { "supplier_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_goods_receipts_tenant_number",
                table: "goods_receipts",
                columns: new[] { "tenant_id", "receipt_number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_purchase_order_items_global_product_id",
                table: "purchase_order_items",
                column: "global_product_id");

            migrationBuilder.CreateIndex(
                name: "ix_purchase_order_items_order_product",
                table: "purchase_order_items",
                columns: new[] { "purchase_order_id", "global_product_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_purchase_order_items_purchase_order_id_tenant_id",
                table: "purchase_order_items",
                columns: new[] { "purchase_order_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_purchase_order_items_tenant_id",
                table: "purchase_order_items",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_purchase_order_items_tenant_id_store_id_global_product_id",
                table: "purchase_order_items",
                columns: new[] { "tenant_id", "store_id", "global_product_id" });

            migrationBuilder.CreateIndex(
                name: "ix_purchase_orders_store_id_tenant_id",
                table: "purchase_orders",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_purchase_orders_supplier_id",
                table: "purchase_orders",
                column: "supplier_id");

            migrationBuilder.CreateIndex(
                name: "ix_purchase_orders_supplier_id_tenant_id",
                table: "purchase_orders",
                columns: new[] { "supplier_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_purchase_orders_tenant_number",
                table: "purchase_orders",
                columns: new[] { "tenant_id", "number" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_purchase_orders_tenant_store_status",
                table: "purchase_orders",
                columns: new[] { "tenant_id", "store_id", "status" });

            migrationBuilder.CreateIndex(
                name: "ix_suppliers_is_active",
                table: "suppliers",
                column: "is_active");

            migrationBuilder.CreateIndex(
                name: "ix_suppliers_tenant_code",
                table: "suppliers",
                columns: new[] { "tenant_id", "code" },
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "goods_receipt_items");

            migrationBuilder.DropTable(
                name: "goods_receipts");

            migrationBuilder.DropTable(
                name: "purchase_order_items");

            migrationBuilder.DropTable(
                name: "purchase_orders");

            migrationBuilder.DropTable(
                name: "suppliers");

            migrationBuilder.DropIndex(
                name: "ix_inventory_movements_reference_unique",
                table: "inventory_movements");

            migrationBuilder.DropSequence(
                name: "procurement_goods_receipt_number_seq");

            migrationBuilder.DropSequence(
                name: "procurement_purchase_order_number_seq");
        }
    }
}
