// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using NetTopologySuite.Geometries;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddConsumerDiscovery : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Explicit so a fresh PostGIS image always has the extension before geography columns.
            migrationBuilder.Sql("CREATE EXTENSION IF NOT EXISTS postgis;");

            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:postgis", ",,");

            migrationBuilder.CreateTable(
                name: "store_service_areas",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    latitude = table.Column<double>(type: "double precision", nullable: false),
                    longitude = table.Column<double>(type: "double precision", nullable: false),
                    service_radius_meters = table.Column<int>(type: "integer", nullable: false),
                    is_enabled = table.Column<bool>(type: "boolean", nullable: false),
                    location = table.Column<Point>(type: "geography (Point, 4326)", nullable: false),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_store_service_areas", x => x.id);
                    table.UniqueConstraint("ak_store_service_areas_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.CheckConstraint("ck_store_service_areas_radius_range", "service_radius_meters BETWEEN 100 AND 50000");
                    table.ForeignKey(
                        name: "fk_store_service_areas_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_store_service_areas_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_store_service_areas_location",
                table: "store_service_areas",
                column: "location")
                .Annotation("Npgsql:IndexMethod", "gist");

            migrationBuilder.CreateIndex(
                name: "ix_store_service_areas_store_id",
                table: "store_service_areas",
                column: "store_id",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_store_service_areas_store_id_tenant_id",
                table: "store_service_areas",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_store_service_areas_tenant_id",
                table: "store_service_areas",
                column: "tenant_id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "store_service_areas");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:PostgresExtension:postgis", ",,");
        }
    }
}
