// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class EnforceStoreFranchiseeTenantIntegrity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_stores_franchisees_franchisee_id",
                table: "stores");

            migrationBuilder.DropIndex(
                name: "ix_stores_franchisee_id",
                table: "stores");

            migrationBuilder.AddUniqueConstraint(
                name: "ak_franchisees_id_tenant_id",
                table: "franchisees",
                columns: new[] { "id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_stores_franchisee_id_tenant_id",
                table: "stores",
                columns: new[] { "franchisee_id", "tenant_id" });

            migrationBuilder.AddForeignKey(
                name: "fk_stores_franchisees_franchisee_id_tenant_id",
                table: "stores",
                columns: new[] { "franchisee_id", "tenant_id" },
                principalTable: "franchisees",
                principalColumns: new[] { "id", "tenant_id" },
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_stores_franchisees_franchisee_id_tenant_id",
                table: "stores");

            migrationBuilder.DropIndex(
                name: "ix_stores_franchisee_id_tenant_id",
                table: "stores");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_franchisees_id_tenant_id",
                table: "franchisees");

            migrationBuilder.CreateIndex(
                name: "ix_stores_franchisee_id",
                table: "stores",
                column: "franchisee_id");

            migrationBuilder.AddForeignKey(
                name: "fk_stores_franchisees_franchisee_id",
                table: "stores",
                column: "franchisee_id",
                principalTable: "franchisees",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
