// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddPaymentsModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddUniqueConstraint(
                name: "ak_orders_id_tenant_store",
                table: "orders",
                columns: new[] { "id", "tenant_id", "store_id" });

            migrationBuilder.CreateTable(
                name: "payment_merchant_configurations",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    provider = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    environment = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    public_key = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    encrypted_private_key = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false),
                    encrypted_integrity_secret = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false),
                    encrypted_events_secret = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false),
                    is_enabled = table.Column<bool>(type: "boolean", nullable: false),
                    version = table.Column<int>(type: "integer", nullable: false),
                    disabled_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_payment_merchant_configurations", x => x.id);
                    table.ForeignKey(
                        name: "fk_payment_merchant_configurations_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "payments",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    order_id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    provider = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    requires_reconciliation = table.Column<bool>(type: "boolean", nullable: false),
                    reconciliation_reason = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    approved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_payments", x => x.id);
                    table.UniqueConstraint("ak_payments_id_tenant_id", x => new { x.id, x.tenant_id });
                    table.CheckConstraint("ck_payments_amount_positive", "amount > 0");
                    table.ForeignKey(
                        name: "fk_payments_orders_order_id_tenant_id_store_id",
                        columns: x => new { x.order_id, x.tenant_id, x.store_id },
                        principalTable: "orders",
                        principalColumns: new[] { "id", "tenant_id", "store_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_payments_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_payments_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "payment_attempts",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    payment_id = table.Column<Guid>(type: "uuid", nullable: false),
                    merchant_configuration_id = table.Column<Guid>(type: "uuid", nullable: false),
                    provider = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    environment = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    merchant_reference = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    provider_transaction_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    provider_raw_status = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    failure_code = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: true),
                    failure_message = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    checkout_action_json = table.Column<string>(type: "character varying(8000)", maxLength: 8000, nullable: true),
                    initiation_started_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    approved_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    declined_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    last_provider_check_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    provider_occurred_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_payment_attempts", x => x.id);
                    table.CheckConstraint("ck_payment_attempts_amount_positive", "amount > 0");
                    table.ForeignKey(
                        name: "fk_payment_attempts_payment_merchant_configurations_merchant_c",
                        column: x => x.merchant_configuration_id,
                        principalTable: "payment_merchant_configurations",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_payment_attempts_payments_payment_id",
                        column: x => x.payment_id,
                        principalTable: "payments",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "payment_provider_events",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    provider = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    environment = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    provider_event_id = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    event_type = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    payload_hash = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: false),
                    payment_attempt_id = table.Column<Guid>(type: "uuid", nullable: true),
                    merchant_configuration_id = table.Column<Guid>(type: "uuid", nullable: true),
                    status = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
                    failure_reason = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    received_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    processed_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    provider_occurred_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_payment_provider_events", x => x.id);
                    table.ForeignKey(
                        name: "fk_payment_provider_events_payment_attempts_payment_attempt_id",
                        column: x => x.payment_attempt_id,
                        principalTable: "payment_attempts",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_payment_provider_events_payment_merchant_configurations_mer",
                        column: x => x.merchant_configuration_id,
                        principalTable: "payment_merchant_configurations",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_payment_attempts_merchant_configuration_id",
                table: "payment_attempts",
                column: "merchant_configuration_id");

            migrationBuilder.CreateIndex(
                name: "ix_payment_attempts_reconciliation",
                table: "payment_attempts",
                columns: new[] { "status", "last_provider_check_at", "created_at" });

            migrationBuilder.CreateIndex(
                name: "ux_payment_attempts_inflight",
                table: "payment_attempts",
                column: "payment_id",
                unique: true,
                filter: "status IN ('Created', 'Initiating', 'Pending', 'Unknown')");

            migrationBuilder.CreateIndex(
                name: "ux_payment_attempts_merchant_reference",
                table: "payment_attempts",
                column: "merchant_reference",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ux_payment_attempts_provider_tx",
                table: "payment_attempts",
                columns: new[] { "provider", "environment", "provider_transaction_id" },
                unique: true,
                filter: "provider_transaction_id IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ux_payment_merchant_cfg_active",
                table: "payment_merchant_configurations",
                columns: new[] { "tenant_id", "provider", "environment" },
                unique: true,
                filter: "is_enabled = TRUE");

            migrationBuilder.CreateIndex(
                name: "ux_payment_merchant_cfg_tenant_provider_env_version",
                table: "payment_merchant_configurations",
                columns: new[] { "tenant_id", "provider", "environment", "version" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_payment_provider_events_merchant_configuration_id",
                table: "payment_provider_events",
                column: "merchant_configuration_id");

            migrationBuilder.CreateIndex(
                name: "ix_payment_provider_events_payment_attempt_id",
                table: "payment_provider_events",
                column: "payment_attempt_id");

            migrationBuilder.CreateIndex(
                name: "ux_payment_provider_events_id",
                table: "payment_provider_events",
                columns: new[] { "provider", "environment", "provider_event_id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "ix_payments_order_id_tenant_id_store_id",
                table: "payments",
                columns: new[] { "order_id", "tenant_id", "store_id" });

            migrationBuilder.CreateIndex(
                name: "ix_payments_requires_reconciliation",
                table: "payments",
                column: "requires_reconciliation",
                filter: "requires_reconciliation = TRUE");

            migrationBuilder.CreateIndex(
                name: "ix_payments_status_created_at",
                table: "payments",
                columns: new[] { "status", "created_at" });

            migrationBuilder.CreateIndex(
                name: "ix_payments_store_id_tenant_id",
                table: "payments",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_payments_tenant_store_created_at",
                table: "payments",
                columns: new[] { "tenant_id", "store_id", "created_at" });

            migrationBuilder.CreateIndex(
                name: "ux_payments_order_id",
                table: "payments",
                column: "order_id",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "payment_provider_events");

            migrationBuilder.DropTable(
                name: "payment_attempts");

            migrationBuilder.DropTable(
                name: "payment_merchant_configurations");

            migrationBuilder.DropTable(
                name: "payments");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_orders_id_tenant_store",
                table: "orders");
        }
    }
}
