// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace YaaJuu.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddPricingModule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddUniqueConstraint(
                name: "ak_store_products_tenant_id_store_id_global_product_id",
                table: "store_products",
                columns: new[] { "tenant_id", "store_id", "global_product_id" });

            migrationBuilder.CreateTable(
                name: "global_product_prices",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    valid_from = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    valid_to = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_global_product_prices", x => x.id);
                    table.CheckConstraint("ck_global_product_prices_amount_positive", "amount > 0");
                    table.ForeignKey(
                        name: "fk_global_product_prices_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "store_product_prices",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    tenant_id = table.Column<Guid>(type: "uuid", nullable: false),
                    store_id = table.Column<Guid>(type: "uuid", nullable: false),
                    global_product_id = table.Column<Guid>(type: "uuid", nullable: false),
                    amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
                    currency = table.Column<string>(type: "character varying(3)", maxLength: 3, nullable: false),
                    valid_from = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    valid_to = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    xmin = table.Column<uint>(type: "xid", rowVersion: true, nullable: false),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_store_product_prices", x => x.id);
                    table.CheckConstraint("ck_store_product_prices_amount_positive", "amount > 0");
                    table.ForeignKey(
                        name: "fk_store_product_prices_global_products_global_product_id",
                        column: x => x.global_product_id,
                        principalTable: "global_products",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_store_product_prices_store_products_tenant_id_store_id_glob",
                        columns: x => new { x.tenant_id, x.store_id, x.global_product_id },
                        principalTable: "store_products",
                        principalColumns: new[] { "tenant_id", "store_id", "global_product_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_store_product_prices_stores_store_id_tenant_id",
                        columns: x => new { x.store_id, x.tenant_id },
                        principalTable: "stores",
                        principalColumns: new[] { "id", "tenant_id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_store_product_prices_tenants_tenant_id",
                        column: x => x.tenant_id,
                        principalTable: "tenants",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_global_product_prices_current",
                table: "global_product_prices",
                column: "global_product_id",
                unique: true,
                filter: "valid_to IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_global_product_prices_product_valid_from",
                table: "global_product_prices",
                columns: new[] { "global_product_id", "valid_from" });

            migrationBuilder.CreateIndex(
                name: "ix_store_product_prices_current",
                table: "store_product_prices",
                columns: new[] { "store_id", "global_product_id" },
                unique: true,
                filter: "valid_to IS NULL");

            migrationBuilder.CreateIndex(
                name: "ix_store_product_prices_global_product_id",
                table: "store_product_prices",
                column: "global_product_id");

            migrationBuilder.CreateIndex(
                name: "ix_store_product_prices_store_id_tenant_id",
                table: "store_product_prices",
                columns: new[] { "store_id", "tenant_id" });

            migrationBuilder.CreateIndex(
                name: "ix_store_product_prices_store_product_valid_from",
                table: "store_product_prices",
                columns: new[] { "store_id", "global_product_id", "valid_from" });

            migrationBuilder.CreateIndex(
                name: "ix_store_product_prices_tenant_id",
                table: "store_product_prices",
                column: "tenant_id");

            migrationBuilder.CreateIndex(
                name: "ix_store_product_prices_tenant_id_store_id_global_product_id",
                table: "store_product_prices",
                columns: new[] { "tenant_id", "store_id", "global_product_id" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "global_product_prices");

            migrationBuilder.DropTable(
                name: "store_product_prices");

            migrationBuilder.DropUniqueConstraint(
                name: "ak_store_products_tenant_id_store_id_global_product_id",
                table: "store_products");
        }
    }
}
