<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Chevrere.Modules.Inventory.Application\Chevrere.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Chevrere.Infrastructure\Chevrere.Infrastructure.csproj" />
  </ItemGroup>
</Project>
