<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Chevrere.Api\Chevrere.Api.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Chevrere.Infrastructure\Chevrere.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Chevrere.SharedKernel\Chevrere.SharedKernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Chevrere.Modules.Identity.Application\Chevrere.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Chevrere.Modules.Identity.Domain\Chevrere.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Chevrere.Modules.Identity.Infrastructure\Chevrere.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\Chevrere.Modules.Subscriptions.Application\Chevrere.Modules.Subscriptions.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\Chevrere.Modules.Subscriptions.Domain\Chevrere.Modules.Subscriptions.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Subscriptions\Chevrere.Modules.Subscriptions.Infrastructure\Chevrere.Modules.Subscriptions.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Tenancy\Chevrere.Modules.Tenancy.Application\Chevrere.Modules.Tenancy.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Tenancy\Chevrere.Modules.Tenancy.Domain\Chevrere.Modules.Tenancy.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Tenancy\Chevrere.Modules.Tenancy.Infrastructure\Chevrere.Modules.Tenancy.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Chevrere.Modules.Catalog.Domain\Chevrere.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Chevrere.Modules.Catalog.Application\Chevrere.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\Chevrere.Modules.Catalog.Infrastructure\Chevrere.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\Chevrere.Modules.Pricing.Domain\Chevrere.Modules.Pricing.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\Chevrere.Modules.Pricing.Application\Chevrere.Modules.Pricing.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pricing\Chevrere.Modules.Pricing.Infrastructure\Chevrere.Modules.Pricing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inventory\Chevrere.Modules.Inventory.Domain\Chevrere.Modules.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inventory\Chevrere.Modules.Inventory.Application\Chevrere.Modules.Inventory.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inventory\Chevrere.Modules.Inventory.Infrastructure\Chevrere.Modules.Inventory.Infrastructure.csproj" />
  </ItemGroup>
</Project>
