<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Chevrere.Modules.Identity.Application\Chevrere.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Chevrere.Infrastructure\Chevrere.Infrastructure.csproj" />
  </ItemGroup>
</Project>
